### ISSUE TITLE
CompactArray could use a constructor from slice

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [vigna/sux-rs#23]
Similar to https://docs.rs/sucds/latest/sucds/int_vectors/compact_vector/struct.CompactVector.html#method.from_slice.

Currently constructing it from existing data requires some overhead.

**Comment by zommiommy** [comment]
Ok, what about an `extend` method that takes a general iterator? The codegen should be the same. 

Ofc there with an ExactSizeIterator we could pre-allocate everything and concurrently build the compact_array by doing compare_exchanges.

**Comment by RagnarGrootKoerkamp** [comment]
Yeah taking an interator sgtm.

**Comment by RagnarGrootKoerkamp** [comment]
Actually, if you construct it from fresh it would be nice to have a `from_iterator() -> Self` that also computes the required bit-width.

**Comment by vigna** [comment]
I'm just adding to common_traits the UnsignedInt.len() method for that purpose (because I need it for another type)!

**Comment by zommiommy** [comment]
> Actually, if you construct it from fresh it would be nice to have a `from_iterator() -> Self` that also computes the required bit-width.

that would require either allocating, or iterating twice

**Comment by RagnarGrootKoerkamp** [comment]
Right, that makes more sense for `from_slice` where you already know you can iterate twice.

(Or you could take a `Iterator + Clone` but that's somewhat unconventional I think.)

**Comment by vigna** [comment]
Implemented in the compact branch,
