### ISSUE TITLE
Random access throughut test should generate randomness up front

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [vigna/sux-rs#24]
You probably want to allocate and fill a vector of random numbers first, and only then start the timed loop where you do the random accesses:

https://github.com/vigna/sux-rs/blob/95b8018c1eeeff138e33b632deb90b04e0f267b7/examples/bench_compact_array.rs#L63

**Comment by vigna** [comment]
You're 100% right. I was using that test mostly for the iterator, so I didn't do the rest properly...
