### ISSUE TITLE
Add `CompactArray::address_of(index: usize) -> *const u64`

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [vigna/sux-rs#26]
Since random memory access is generally slow, I'm speeding up my implementation by prefetching cachelines for a few (16) iterations ahead, see [here](https://github.com/RagnarGrootKoerkamp/pthash-rs/blob/8143c4da76a8a524bcae7e4e7d6c59e6712f2bd2/src/index.rs#L7) and [here](https://github.com/RagnarGrootKoerkamp/pthash-rs/blob/8143c4da76a8a524bcae7e4e7d6c59e6712f2bd2/src/pack.rs#L24). For `Vec<u64>` this brings the inverse throughput (time per iteration) down from `18ns` to `7ns` and for `Vec<u8>` it goes from `17ns` to `6ns`.

Would be cool if you could add a similar method here -- I don't think I will be able to get its performance close to that of `Vec` without being able to prefetch.

**Comment by vigna** [comment]
Just added to BitFieldVec (the artist formerly known as CompactArray) in the "compact" branch.
