### ISSUE TITLE
`TmpDir` needs customization

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [vigna/sux-rs#28]
At least on Archlinux, `/tmp` is a `tempfs` and hence in RAM, and limited in size to half the available memory. Solaris and Fedora also do this apparently.

For me to use `SigStore` I'd like to provide a custom directory for the temporary files.

https://github.com/vigna/sux-rs/blob/e081b427f99eeb5ce127dc74c5c03cd0862912c2/src/utils/sig_store.rs#L348

**Comment by zommiommy** [comment]
iirc it can be customized with the TMPDIR env var

**Comment by RagnarGrootKoerkamp** [comment]
oh right; that may be sufficient indeed. Would be good to document this.

**Comment by zommiommy** [comment]
yeah its in `std::env::tmp_dir` but I forget every time

**Comment by vigna** [comment]
Yes, I think of doing it every time and then I forget. It might be useful to have a settable temp dir tho.
