### ISSUE TITLE
`Derive(MemDbg)` makes trait non-object safe

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [vigna/sux-rs#55]
`MemDbg:mem_dbg{,_depth}_on` functions take a `&mut impl Write`, which prevent doing `&dyn MyTrait` when `MyTrait: MemDbg`.

Not quite sure what a good fix is though. Clearly you want to provide the custom writer functionality.

**Comment by zommiommy** [comment]
I think the easiest solution is to pass around the writer as owned instead of taking the reference

**Comment by RagnarGrootKoerkamp** [comment]
You could also take a `&mut dyn Write`, but that could be considered ugly in cases where it's not necessary.

**Comment by RagnarGrootKoerkamp** [comment]
Oh probably it would make more sense for the default `mem_dbg` function to write to `stderr` rather than `stdout`.
