### ISSUE TITLE
`MemDbg` improvements

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [vigna/sux-rs#56]
This stuff is really cool! I've been adding similar functions to my own types before but having a common trait around it is so much better :)

Some suggestions to improve it:
- Print to `stderr` by default, since this is not meant to be machine-readable.
- Add support for coloured output? Especially the type names could be easier to distinguish from the rest, and maybe have different colours for `bytes` (white) `kB` (green) `MB` (yellow) and `GB` (red)?
- The `SEPARATOR` flag doesn't do anything when `HUMAN_READABLE` is passed. Pretty obvious but could be documented.
- For types containing a large allocation, I don't usually care much about the stack/inline space they consume. Since I don't think you support nested allocations anyway currently (`Vec<Vec<usize>>`), I think a flag to hide 'stack' variables would be nice.

I could probably try to PR some of these if you think they are a good idea.

(Oh I'm in the wrong repo; sorry.)

**Comment by RagnarGrootKoerkamp** [comment]
What I have now to fix the first 3 points. Will also add something for the last.
![image](https://github.com/user-attachments/assets/14a08ed2-e143-485e-b8d4-f66ac21a884a)

**Comment by zommiommy** [comment]
That does look very good, I'm ok with stderr by default.

**Comment by zommiommy** [comment]
Lets move it a memdbg repo lol for  the stack filter maybe we could have a min dimension filter? Like only consider fields over x bytes
